name = "kazoottt-blog"
compatibility_date = "2024-01-01"

[build]
command = "pnpm build"

[build.upload]
format = "directory"

[site]
bucket = "./dist"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "blog-pageviews"
database_id = "${D1_DATABASE_ID}"